name:  Shell Commands

on:
  #schedule:
  #- cron: '30 11 * * *'
  push:
    branches:
      - main
    paths:
      #- 'dbscripts/**'
      - '!.github/workflows/DemoDeploy.yml'
     
  workflow_dispatch:
- '.github/workflows/sample.yml'
jobs:  
  runs-shell-commands:
    runs-on:  ubuntu-latest
    steps:
      - name: echo a string
        run:  echo "This is a string"
      - name: multi commands
        run: |
          git -v
          npm -v
          echo It is done
