name:  "Shell Commands"

on:
  push:
    branches:
      - main
    paths:
      -  '.github/workflows/sample.yml'
  workflow_dispatch:	
jobs:
  runs-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: "simple echo cmd"
        run: echo "hellow world"
      - name: multi cmd
        run: |
          git -v
          npm -v
          echo It is done
